// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Courses documents */
interface CoursesDocumentData {
    /**
     * title field in *Courses*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: courses.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * description field in *Courses*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: courses.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * image field in *Courses*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: courses.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * discipline1 field in *Courses*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: courses.discipline1
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    discipline1: prismicT.KeyTextField;
    /**
     * discipline2 field in *Courses*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: courses.discipline2
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    discipline2: prismicT.KeyTextField;
    /**
     * discipline3 field in *Courses*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: courses.discipline3
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    discipline3: prismicT.KeyTextField;
    /**
     * discipline4 field in *Courses*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: courses.discipline4
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    discipline4: prismicT.KeyTextField;
    /**
     * discipline5 field in *Courses*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: courses.discipline5
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    discipline5: prismicT.KeyTextField;
    /**
     * discipline6 field in *Courses*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: courses.discipline6
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    discipline6: prismicT.KeyTextField;
    /**
     * totalValue field in *Courses*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: courses.totalvalue
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    totalvalue: prismicT.KeyTextField;
    /**
     * saleValue field in *Courses*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: courses.salevalue
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    salevalue: prismicT.KeyTextField;
    /**
     * duration field in *Courses*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: courses.duration
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    duration: prismicT.KeyTextField;
    /**
     * grau field in *Courses*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: courses.grau
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    grau: prismicT.KeyTextField;
    /**
     * modalidade field in *Courses*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: courses.modalidade
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    modalidade: prismicT.KeyTextField;
    /**
     * turn field in *Courses*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: courses.turn
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    turn: prismicT.KeyTextField;
}
/**
 * Courses document from Prismic
 *
 * - **API ID**: `courses`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CoursesDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<CoursesDocumentData>, "courses", Lang>;
/** Content for Images documents */
interface ImagesDocumentData {
    /**
     * image field in *Images*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: images.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Images document from Prismic
 *
 * - **API ID**: `images`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImagesDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ImagesDocumentData>, "images", Lang>;
/** Content for Posts documents */
interface PostsDocumentData {
    /**
     * title field in *Posts*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: posts.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * content field in *Posts*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: posts.content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * image field in *Posts*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: posts.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * author field in *Posts*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: posts.author
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    author: prismicT.KeyTextField;
}
/**
 * Posts document from Prismic
 *
 * - **API ID**: `posts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PostsDocumentData>, "posts", Lang>;
export type AllDocumentTypes = CoursesDocument | ImagesDocument | PostsDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { CoursesDocumentData, CoursesDocument, ImagesDocumentData, ImagesDocument, PostsDocumentData, PostsDocument, AllDocumentTypes };
    }
}
