import { GetStaticProps } from 'next'
import Head from 'next/head'
import HomeMain from '../components/Home/HomeMain'
import { getClient } from '../services/prismic'
import styles from '../styles/home.module.scss'



export interface PostsProps {
  posts: {
    id: string,
    title: string,
    avatar: string,
    content: string,
    image: string,
    updatedAt: string,
    author?: string,
  }
}

export default function Home({posts}: PostsProps) {
console.log(posts)

  return (
    
    <>

      <Head>
        <title>Inicio | FAZAG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mainContainer}>
        <HomeMain posts={posts}/>
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {

const response = await getClient().getFirst()
console.log(response)
const posts = {
  id: response.uid,
  title: response.data.title,
  content: response.data.content.find((index: {type: string}) => index.type === 'paragraph')?.text ?? '',
  image: response.data.image.url,
  author: response.data.author,
  updatedAt: new Date(response.last_publication_date).toLocaleDateString('pt-br', {day: "2-digit", month: "long", year: "numeric"})
}

return {
  props: {
    posts
  }
}
}
